version: '3'

services:
  app:
    image: adminer
    restart: always
    ports:
      - 12001:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pointdopao
    ports:
      - "12002:5432"
    
    volumes:
      - ./db:/var/lib/data
